---
title: "Examen_I_G1_C4H522"
format:
  html:
    embed-resources: true   
    code-fold: false        
execute:
  echo: true                
  warning: false            
  message: false 
---

## 1. Cargar la data
```{r, warning=FALSE, message=FALSE}
library(here)
library(dplyr)

data.original<- read.table(
  here("data", "moras.txt"),
  header = TRUE,
  sep = ","
)

moras <- read.table(
  here("data", "moras.txt"),
  header = TRUE,
  sep = ","
)

View(moras)
```

## 2. Resumen de 5 números
```{r, warning=FALSE, message=FALSE}

#install.packages("modeest")
library(modeest)
library(stringr)

moras <- moras %>% 
  mutate(
    SALARIO = SALARIO %>% 
      str_replace(",", ".") %>% 
      as.numeric()
  )

resumen <- moras %>% 
  summarise(
    moda.salario = mfv(SALARIO, na.rm = TRUE),
    prom.salario = mean(SALARIO, na.rm = TRUE),
    mediana.salario = median(SALARIO, na.rm = TRUE),
    desv.salario = sd(SALARIO, na.rm = TRUE),
    min.salario = min(SALARIO, na.rm = TRUE),
    max.salario = max(SALARIO, na.rm = TRUE),
    moda.edad = mfv(EDAD, na.rm = TRUE),
    prom.edad = mean(EDAD, na.rm = TRUE),
    mediana.edad = median(EDAD, na.rm = TRUE),
    desv.edad = sd(EDAD, na.rm = TRUE),
    min.edad = min(EDAD, na.rm = TRUE),
    max.edad = max(EDAD, na.rm = TRUE)
  )

resumen

str(moras)
```
## 3. Valores atípicos

```{r, warning=FALSE, message=FALSE}
prom.salario <- mean(moras$SALARIO, na.rm = TRUE)
desv.salario <- sd(moras$SALARIO, na.rm = TRUE)

prom.edad <- mean(moras$EDAD, na.rm = TRUE)
desv.edad <- sd(moras$EDAD, na.rm = TRUE)

moras <- moras %>% 
  mutate(
    Z.Score.Salario = (SALARIO-prom.salario)/desv.salario,
    Atípico.salario = ifelse(Z.Score.Salario > 1.96, "Atípico", "No atípico"),
    Z.Score.Edad = (EDAD-prom.edad)/desv.edad,
    Atípico.edad = ifelse(Z.Score.Edad > 1.96, "Atípico", "No atípico")
  )

moras %>% 
  select(Z.Score.Salario, Atípico.salario, Z.Score.Edad, Atípico.edad)
```

## 4. Porcentaje de valores faltantes
```{r, warning=FALSE, message=FALSE}
porc.na <- data.original %>% 
  summarise(across(everything(), ~ mean(is.na(.))*100))

porc.na
```

## 5. Imputar valores faltantes
```{r, warning=FALSE, message=FALSE}
#Para variables numericas
moras <- moras %>%
  mutate(
    EDAD = ifelse(
      is.na(EDAD),
      median(EDAD, na.rm = TRUE),
      EDAD
    ),
    SALARIO = ifelse(
      is.na(SALARIO),
      median(SALARIO, na.rm = TRUE),
      SALARIO
    )
  )

#Para variables categóricas

moda.tipo <- mfv(moras$TIPO_ASEGURAMIENTO)

moras <- moras %>%
  mutate(
    TIPO_ASEGURAMIENTO = ifelse(
      is.na(TIPO_ASEGURAMIENTO),
      moda.tipo,
      TIPO_ASEGURAMIENTO
    )
  )

#Comprobación de que no quedan NA's
porc.na.moras <- moras %>% 
  select(-Z.Score.Salario, -Z.Score.Edad, -Atípico.salario, -Atípico.edad) %>% 
  summarise(across(everything(), ~ mean(is.na(.))*100))

porc.na.moras

```

## 6. Gráficos de cantidad de individuos por categoría

```{r, warning=FALSE, message=FALSE}
library(ggplot2)

#Individuos por sexo
moras %>% 
  ggplot(aes(x = SEXO)) +
  geom_bar(fill = "#FADADD") +
  labs(title = "Cantidad de individuos por sexo", 
       x = "Sexo", 
       y = "Cantidad") +
    theme_minimal()

#Individuos por tipo de aseguramiento. Para mayor legibilidad, se invirtiron los ejes de manera que se observen bien los nombres del tipo de aseguramiento

moras %>% 
  ggplot(aes(x = TIPO_ASEGURAMIENTO)) +
  geom_bar(fill = "#FF9AA2") +
  coord_flip() +
  labs(title = "Cantidad por tipo de aseguramiento",
       x = "Tipo de aseguramiento",
       y = "Cantidad") +
  theme_minimal()

#Individuos por sector
moras %>% 
  ggplot(aes(x = SECTOR)) +
  geom_bar(fill = "#C2185B") +
  labs(title = "Cantidad de individuos por sector",
       x = "Sector",
       y = "Cantidad") +
  theme_minimal()

#Individuos por indicador moroso

moras %>% 
  count(INDICADOR_MOROSO) %>% 
  mutate(label = n) %>%
  ggplot(aes(x = "", y = n, fill = as.factor(INDICADOR_MOROSO))) +
  geom_col(color = "white") +
  geom_text(aes(label = label),
            position = position_stack(vjust = 0.5),
            color = "white", size = 5) +
  coord_polar(theta = "y") +
  scale_fill_manual(
    values = c("#FADADD", "#C2185B"),
    name   = "Moroso",
    labels = c("0 = No moroso", "1 = Moroso")
  ) +
  labs(
    title = "Cantidad de individuos morosos vs no morosos"
  ) +
  theme_void()

#Individuos por indicador activo

moras %>% 
  count(INDICADOR_ACTIVO) %>% 
  mutate(label = n) %>%
  ggplot(aes(x = "", y = n, fill = as.factor(INDICADOR_ACTIVO))) +
  geom_col(color = "white") +
  geom_text(aes(label = label),
            position = position_stack(vjust = 0.5),
            color = "white", size = 5) +
  coord_polar(theta = "y") +
  scale_fill_manual(
    values = c("#FFB3C6", "#9B59B6"),
    name   = "Activo",
    labels = c("0 = Inactivo", "1 = Activo")
  ) +
  labs(
    title = "Proporción de asegurados activos vs inactivos"
  ) +
  theme_void()

#Individuos por indicador extrajero

moras %>% 
  count(INDICADOR.EXTRANJERO) %>% 
  mutate(label = n)%>%
  ggplot(aes(x = "", y = n, fill = as.factor(INDICADOR.EXTRANJERO))) +
  geom_col(color = "white") +
  geom_text(aes(label = label),
            position = position_stack(vjust = 0.5),
            color = "white", size = 5) +
  coord_polar(theta = "y") +
  scale_fill_manual(
    values = c("#F7C6D0", "#E91E63"),
    name   = "Extranjero",
    labels = c("0 = Nacional", "1 = Extranjero")
  ) +
  labs(
    title = "Cantidad de individuos nacionales vs extranjeros"
  ) +
  theme_void()
```
## 7. Gráficos de variables categóricas usando porcentajes

```{r, warning=FALSE, message=FALSE}

#Porcentaje de morosidad por sexo
moras %>%
  group_by(SEXO) %>%
  summarise(
    porcentaje.moroso = mean(INDICADOR_MOROSO == "SI", na.rm = TRUE) * 100
  ) %>%
  ggplot(aes(x = SEXO, y = porcentaje.moroso)) +
  geom_col(fill = "#FADADD") +
  labs(
    title = "Porcentaje de morosidad por sexo",
    x = "Sexo",
    y = "% de personas en estado de morosidad"
  ) +
  theme_minimal()

#Porcentaje de morosidad por tipo de aseguramiento
moras %>%
  group_by(TIPO_ASEGURAMIENTO) %>%
  summarise(
    porcentaje.moroso = mean(INDICADOR_MOROSO == "SI", na.rm = TRUE) * 100
  ) %>%
  ggplot(aes(x = porcentaje.moroso, y = TIPO_ASEGURAMIENTO)) +
  geom_col(fill = "#FF9AA2") +
  labs(
    title = "Porcentaje de morosidad por tipo de aseguramiento",
    x = "% de personas en estado de morosidad",
    y = "Tipo de aseguramiento"
  ) +
  theme_minimal()

#Porcentaje de morosidad por indicador moroso
moras %>% 
  count(INDICADOR_MOROSO) %>% 
  mutate(
    prop  = n / sum(n),
    label = paste0(round(prop * 100, 1), "%")
  ) %>%
  ggplot(aes(x = "", y = prop, fill = INDICADOR_MOROSO)) +
  geom_col(color = "white") +
  geom_text(aes(label = label),
            position = position_stack(vjust = 0.5),
            color = "white", size = 5) +
  coord_polar(theta = "y") +
  scale_fill_manual(
    values = c("NO" = "#FADADD", "SI" = "#C2185B"),
    name   = "Moroso"
  ) +
  labs(title = "Porcentaje de morosos vs no morosos") +
  theme_void() 

#Porcentaje de morosidad por indicador activo
moras %>% 
  count(INDICADOR_ACTIVO) %>% 
  mutate(
    prop  = n / sum(n),
    label = paste0(round(prop * 100, 1), "%")
  ) %>%
  ggplot(aes(x = "", y = prop, fill = INDICADOR_ACTIVO)) +
  geom_col(color = "white") +
  geom_text(aes(label = label),
            position = position_stack(vjust = 0.5),
            color = "white", size = 5) +
  coord_polar(theta = "y") +
  scale_fill_manual(
    values = c("NO" = "#FFB3C6", "SI" = "#9B59B6"),
    name   = "Activo"
  ) +
  labs(title = "Porcentaje de individuos activos vs inactivos") +
  theme_void()

#Porcentaje de morosidad por indicador extranjero
moras %>% 
  count(INDICADOR.EXTRANJERO) %>% 
  mutate(
    prop  = n / sum(n),
    label = paste0(round(prop * 100, 1), "%")
  ) %>%
  ggplot(aes(x = "", y = prop, fill = INDICADOR.EXTRANJERO)) +
  geom_col(color = "white") +
  geom_text(aes(label = label),
            position = position_stack(vjust = 0.5),
            color = "white", size = 5) +
  coord_polar(theta = "y") +
  scale_fill_manual(
    values = c("NO" = "#F7C6D0", "SI" = "#E91E63"),
    name   = "Extranjero"
  ) +
  labs(title = "Porcentaje de nacionales vs extranjeros") +
  theme_void() 

```
## 8. 
```{r}
cuartiles_salario <- quantile(moras$SALARIO,
                              probs = seq(0, 1, 0.25),
                              na.rm = TRUE)

moras.cat <- moras %>%
  mutate(
    rango.edad = cut(
      EDAD,
      breaks = c(0, 25, 35, 45, 55, Inf),
      right  = FALSE,
      labels = c("0–24", "25–34", "35–44", "45–54", "55+")
    ),
    rango.salario = cut(
      SALARIO,
      breaks = cuartiles_salario,
      include.lowest = TRUE,
      labels = c("Q1", "Q2", "Q3", "Q4")
    )
  )

#Porcentaje de morosidad por rangos de salario
moras.cat %>%
  group_by(rango.edad, INDICADOR_MOROSO) %>%
  summarise(
    n = n(),
    .groups = "drop"
  ) %>%
  group_by(rango.edad) %>%
  mutate(
    porc = n / sum(n) * 100
  ) %>%
  ggplot(aes(x = rango.edad, y = porc, fill = INDICADOR_MOROSO)) +
  geom_col() +
  scale_fill_manual(
    values = c("NO" = "#FADADD", "SI" = "#C2185B"),
    name   = "Moroso"
  ) +
  labs(
    title = "Porcentaje de morosidad por rango de edad",
    x = "Rango de edad",
    y = "% de personas en estado de morosidad / no morosidad"
  ) +
  theme_minimal()

#Porcentaje de morosidad por cuartitl de salario
moras.cat %>%
  group_by(rango.salario, INDICADOR_MOROSO) %>%
  summarise(
    n = n(),
    .groups = "drop"
  ) %>%
  group_by(rango.salario) %>%
  mutate(
    porc = n / sum(n) * 100
  ) %>%
  ggplot(aes(x = rango.salario, y = porc, fill = INDICADOR_MOROSO)) +
  geom_col() +
  scale_fill_manual(
    values = c("NO" = "#FADADD", "SI" = "#C2185B"),
    name   = "Moroso"
  ) +
  labs(
    title = "Porcentaje de morosidad por cuartil de salario",
    x = "Cuartil de salario",
    y = "% de personas en estado de morosidad / no morosidad"
  ) +
  theme_minimal()
```

